[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "SNEK2"
description = "The Super NPC/Event Koordinator 2"
readme = "README.md"
requires-python = ">=3.11"
license  = {text = "MIT"}

version = "2.0.1"
